/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JogoPersonagem;

import java.util.Random;
import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {

        Random rand = new Random();

        String[] nomes_inimigos = new String[5];
        nomes_inimigos[0] = "Orc";
        nomes_inimigos[1] = "Dragao";
        nomes_inimigos[2] = "Mago Negro";
        nomes_inimigos[3] = "Esqueleto";
        nomes_inimigos[4] = "Kobold";

        Inimigo[] inimigos_disponiveis = new Inimigo[10];
        for (int i = 0; i < inimigos_disponiveis.length; i++) {

            int pos_nomesorteado = rand.nextInt(nomes_inimigos.length);
            String nome_sorteado = nomes_inimigos[pos_nomesorteado];

            int energia_sort = rand.nextInt(20) + 1;
            int vida_sort = rand.nextInt(100) + 1;
            int dano_sort = rand.nextInt(10) + 1;

            inimigos_disponiveis[i] = new Inimigo(nome_sorteado, energia_sort, vida_sort, dano_sort);
            
            System.out.println(inimigos_disponiveis[i].toString());
        }

        Player jogador = new Player("Thor", 10, 5, 0);

        //jogador.fome = 2121212121;
        jogador.setFome(2121212121);
        do {
            String opcao = JOptionPane.showInputDialog(
                    "#### Personagem: " + jogador.getNome() + " ####"
                    + "\n" + jogador.toString()
                    + "\n"
                    + "\n1 - Comer"
                    + "\n2 - Dormir"
                    + "\n3 - Caçar");

            switch (opcao) {
                case "1":
                    jogador.comer();
                    break;
                case "2":
                    jogador.dormir();
                    break;
                case "3":
                    jogador.cacar();
                    break;
                case "999":
                default:
                    JOptionPane.showMessageDialog(null, "Opção Invalida.");
            }

            double chanceInimigo = rand.nextDouble();
            if (chanceInimigo <= 0.10) {
                Inimigo enemy = new Inimigo("Orc", 10, 50, 10);

                jogador.recebeDano(enemy.getDano());
            }

        } while (jogador.isAlive());

        JOptionPane.showMessageDialog(null, "#####GAME OVER #####");

        
        
        
        
        
        
        
    }
}
