use db_pessoas;

CREATE TABLE TUSUARIO (
USU_LOGIN CHAR(100) NOT NULL,
USU_SENHA CHAR(100) NOT NULL,
USU_NOME CHAR(100) NOT NULL,
CONSTRAINT PRIMARY KEY TUSUARIO_PK (USU_LOGIN)
);


INSERT INTO TUSUARIO VALUES ('PEDRO','123456','PEDRO YURI');