/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aula_logincompleto.Telas;

import com.mycompany.aula_logincompleto.DAO.Tcursos_DAO;
import com.mycompany.aula_logincompleto.Model.Cursos;
import java.util.ArrayList;

/**
 *
 * @author SAMSUNG
 */
public class Tela_Cursos extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cursos
     */
    public Tela_Cursos() {
        initComponents();

        ArrayList<Cursos> listaDB = new ArrayList<Cursos>();

        
        listaDB = Cursos.listarTodos();
        /*
        listaDB.add(new Cursos(1, "Analise e desenvolvimento de Sistemas", 5));
        listaDB.add(new Cursos(2, "Sistemas de Informação", 8));
        listaDB.add(new Cursos(3, "Ciencias da Computação", 8));
*/
        cmb_registros.addItem(new Cursos(0, "Selecione...", 0));
        for (int c = 0; c < listaDB.size(); c++) {
            cmb_registros.addItem(listaDB.get(c));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txi_id = new javax.swing.JTextField();
        txi_nome = new javax.swing.JTextField();
        txi_qtdSemestres = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        cmb_registros = new javax.swing.JComboBox<>();
        btn_voltar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txi_id.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        txi_id.setEnabled(false);
        txi_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txi_idActionPerformed(evt);
            }
        });

        txi_nome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        txi_nome.setEnabled(false);

        txi_qtdSemestres.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtd. Semestre"));
        txi_qtdSemestres.setEnabled(false);

        btn_cadastrar.setText("Novo");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.setEnabled(false);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.setToolTipText("");
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        cmb_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_registrosActionPerformed(evt);
            }
        });

        btn_voltar.setText("Menu");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_registros, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txi_id, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txi_nome)
                            .addComponent(txi_qtdSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_voltar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cmb_registros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txi_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txi_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txi_qtdSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_salvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_voltar)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txi_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txi_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txi_idActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        Tela_Menu tela_menu = new Tela_Menu();
        tela_menu.setVisible(true);
        tela_menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        setStateTela("INCLUIR");
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        setValuesTela(null);
        setStateTela("CANCELAR");
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cmb_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_registrosActionPerformed
        // TODO add your handling code here:

        if (cmb_registros.getSelectedIndex() > 0) {
            Cursos cursoSelect = (Cursos) cmb_registros.getSelectedItem();
            setValuesTela(cursoSelect);
            setStateTela("ALTERAR");
        } else {
            setValuesTela(null);
            setStateTela("PADRAO");
        }
    }//GEN-LAST:event_cmb_registrosActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:

        Cursos cursoTela = new Cursos(0, txi_nome.getText(), Integer.parseInt(txi_qtdSemestres.getText()));

        cursoTela.inserir();

    }//GEN-LAST:event_btn_salvarActionPerformed

    public void setValuesTela(Cursos curso) {

        if (curso != null) {
            txi_id.setText(String.valueOf(curso.getId()));
            txi_nome.setText(curso.getNome());
            txi_qtdSemestres.setText(String.valueOf(curso.getQtdeSem()));
        } else {
            cmb_registros.setSelectedIndex(0);
            txi_id.setText("");
            txi_nome.setText("");
            txi_qtdSemestres.setText("");
        }
    }

    public void setStateTela(String state) {
        switch (state) {
            case "INCLUIR":
                txi_id.setEnabled(true);
                txi_nome.setEnabled(true);
                txi_qtdSemestres.setEnabled(true);
                btn_cadastrar.setEnabled(false);
                btn_salvar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                break;
            case "ALTERAR":
                txi_id.setEnabled(false);
                txi_nome.setEnabled(true);
                txi_qtdSemestres.setEnabled(true);
                btn_cadastrar.setEnabled(false);
                btn_salvar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                break;
            case "PADRAO":
            default:
                txi_id.setEnabled(false);
                txi_nome.setEnabled(false);
                txi_qtdSemestres.setEnabled(false);
                btn_cadastrar.setEnabled(true);
                btn_salvar.setEnabled(false);
                btn_cancelar.setEnabled(false);
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<Cursos> cmb_registros;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txi_id;
    private javax.swing.JTextField txi_nome;
    private javax.swing.JTextField txi_qtdSemestres;
    // End of variables declaration//GEN-END:variables
}
